// <auto-generated />
using HumanRisks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HumanRisks.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HumanRisks.Models.RiskAssessment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("RiskAssessments");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Latitude = 0.10000000000000001,
                            Longitude = 0.20000000000000001,
                            Title = "Test"
                        },
                        new
                        {
                            Id = "2",
                            Latitude = 3.0,
                            Longitude = 77.5,
                            Title = "XPPR"
                        },
                        new
                        {
                            Id = "3",
                            Latitude = 4.3099999999999996,
                            Longitude = 4.2000000000000002,
                            Title = "GP"
                        });
                });

            modelBuilder.Entity("HumanRisks.Models.Threat", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Level");

                    b.Property<string>("RiskAssessmentId")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RiskAssessmentId");

                    b.ToTable("Threats");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Level = 1,
                            RiskAssessmentId = "1",
                            Title = "T1"
                        },
                        new
                        {
                            Id = "2",
                            Level = 0,
                            RiskAssessmentId = "1",
                            Title = "T2"
                        },
                        new
                        {
                            Id = "3",
                            Level = 2,
                            RiskAssessmentId = "2",
                            Title = "T3"
                        });
                });

            modelBuilder.Entity("HumanRisks.Models.Threat", b =>
                {
                    b.HasOne("HumanRisks.Models.RiskAssessment", "RiskAssessment")
                        .WithMany("Threats")
                        .HasForeignKey("RiskAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
